language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python app.py
before_install:
- openssl aes-256-cbc -K $encrypted_68431c5bd936_key -iv $encrypted_68431c5bd936_iv
  -in config.json.enc -out config.json -d
